### ISSUE TITLE
Form Border Style Fixed Single not work

### ISSUE THREAD

**Issue by KHALED-ALSHAMMARI** [Taiizor/ReaLTaiizor#123]
### Bug explanation

Welcome
Form Border Style Fixed Single not work
Single static form border style not working
I can control the window with the mouse
Thank you and for your efforts. Good luck
![issue](https://github.com/Taiizor/ReaLTaiizor/assets/143202948/aa4e5390-ea49-4258-8b9f-78a8c0015ce7)

### Version

3.7.9.4

**Comment by Taiizor** [comment]
Instead of FormBorderStyle, Material Form has FormStyle type.

![image](https://github.com/Taiizor/ReaLTaiizor/assets/41683699/a06fe326-bfa4-41a7-830e-8b83a9df8fee)
![image](https://github.com/Taiizor/ReaLTaiizor/assets/41683699/706c7b55-f9b1-4bfa-8468-81dc46857a37)

For the Material Form resize setting, there is a Sizable type.

![image](https://github.com/Taiizor/ReaLTaiizor/assets/41683699/91120654-d9b6-420d-9d92-ec634510d694)

**Comment by KHALED-ALSHAMMARI** [comment]
It is not possible to actually resize the window with the mouse after disabling this option
![image](https://github.com/Taiizor/ReaLTaiizor/assets/143202948/4deb021e-4a4e-437a-8c92-07473ed092de)
Thanks Tezor
Best regards and good luck
