### ISSUE TITLE
Buttons support shortcut keys

### ISSUE THREAD

**Issue by FreeVB** [Taiizor/ReaLTaiizor#52]
How to make buttons support shortcut keys？

**Comment by Taiizor** [comment]
I showed you how to do it in the project below.

[ShortcutKey.zip](https://github.com/Taiizor/ReaLTaiizor/files/8460495/ShortcutKey.zip)
![image](https://user-images.githubusercontent.com/41683699/162653081-f308565f-e831-45b3-88a1-7e11eb4ffd36.png)

**Comment by FreeVB** [comment]
Sorry, I may not have made it clear. I mean to add shortcut keys to the button, just like an ordinary button, like the picture below.
![tt](https://user-images.githubusercontent.com/30093956/162681384-fe94f3a2-818f-44b8-8abe-a846d84c6225.png)

**Comment by FreeVB** [comment]
Just like the system button below, the underline will be displayed under the letter "t", and press Alt + T to respond to the event.

**Comment by Taiizor** [comment]
I understand the problem now. It works on some components. But the first character is not underlined.

![ShortcutKey](https://user-images.githubusercontent.com/41683699/162733716-f5776b22-6413-4608-b990-80d8984ef38e.png)

I will not do anything to fix this problem. Because there are too many components. I can't spend that much time on this project.

My suggestion is to create underline text from the website below and name the button. You then create shortcuts using MethodA or MethodB.

https://yaytext.com/underline

![ShortcutSampleKey](https://user-images.githubusercontent.com/41683699/162736466-ebe964a3-91f2-422c-80c8-41b052564d10.png)

[ShortcutKey.zip](https://github.com/Taiizor/ReaLTaiizor/files/8463797/ShortcutKey.zip)

**Comment by FreeVB** [comment]
In protected override void onpaint (painteventargs E), this can achieve the same effect as the system button, but it does not respond after pressing the shortcut key.
`
StringFormat sf = new(StringFormatFlags.NoWrap | StringFormatFlags.NoClip);
            if (ShowKeyboardCues)
                sf.HotkeyPrefix = System.Drawing.Text.HotkeyPrefix.Show;
            else
                sf.HotkeyPrefix = System.Drawing.Text.HotkeyPrefix.Hide;
            sf.Alignment = StringAlignment.Center;
            sf.LineAlignment = StringAlignment.Center;
`

**Comment by Taiizor** [comment]
MaterialButton now supports it.
