### ISSUE TITLE
MetroControlBox ignores Maximize and Minimize settings

### ISSUE THREAD

**Issue by rrirower** [Taiizor/ReaLTaiizor#81]
### Bug explanation

The MetrolControlBox control ignores the 'MaximizeBox' and 'MinimizeBox' switches in the form designer.  Setting the values to 'false' does not make the Maizmize and Minize boxes hide as it does in a standard Windows Form control.  I also tried setting the values in the code and this did not work.  Additionally, there doesn't appear to be a way to tell what button has been clicked.

### Version

3.7.8.8

**Comment by Taiizor** [comment]
MetroControlBox has its own settings.

![image](https://user-images.githubusercontent.com/41683699/195919496-d1e408cc-ed1a-4ba1-b2c4-e74b18f4c58b.png)

**Comment by rrirower** [comment]
I'm using those settings.  They don't seem to affect the control.

![Capture](https://user-images.githubusercontent.com/34550407/195924838-222fcf82-5c76-4544-8332-d345100ba31b.PNG)

**Comment by Taiizor** [comment]
Its visibility is not lost, it just disables its function.

![image](https://user-images.githubusercontent.com/41683699/195927197-ecb699e4-7da1-4474-94fc-d851c4411931.png)

**Comment by rrirower** [comment]
Ok, I can accept that.  But, how do I know what button is pressed if I enable all three buttons?  I checked the Click event and I could not tell the exact button that was clicked.

**Comment by Taiizor** [comment]
The component is already processing itself according to what is clicked. The user is not notified of the click event. Because it is not needed for this component.

If it is a very necessary situation, there is information on how the click event is performed on the back of the component. For the normal click event, you can take action yourself according to where the mouse clicked according to the X and Y positions.

https://github.com/Taiizor/ReaLTaiizor/blob/develop/src/ReaLTaiizor/Controls/ControlBox/MetroControlBox.cs#L445
https://github.com/Taiizor/ReaLTaiizor/blob/develop/src/ReaLTaiizor/Controls/ControlBox/MetroControlBox.cs#L478

**Comment by rrirower** [comment]
Thanks for the assistance and explanation.
